eureka:
  client:
    service-url:
      defaultZone: http://localhost:8076/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8086

spring:
  application:
    name: "api-gateway"
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: email-service
          uri: http://localhost:8085/
          predicates:
            - Path=/emailservice/**

        - id: slot-booking-service
          uri: http://localhost:8089/
          predicates:
            - Path=/slotbookingservice/**

        - id: review-service
          uri: http://localhost:8088/
          predicates:
            - Path=/reviewservice/**

        - id: payment-service
          uri: http://localhost:8087/
          predicates:
            - Path=/paymentservice/**

        - id: Owner-service
          uri: http://localhost:8086/
          predicates:
            - Path=/ownerService/**

        - id: customer-service
          uri: http://localhost:8084/
          predicates:
            - Path=/customerservice/**

        - id: authentication-service
          uri: http://localhost:8083/
          predicates:
            - Path=/authenticationservice/**

        - id: user-service
          uri: http://localhost:8091/
          predicates:
            - Path=/userservice/**








