eureka:
  client:
    service-url:
      defaultZone: http://localhost:8076/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8086

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    compatibility-verifier:
      enabled: false
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:

        - id: user-service
          uri: http://localhost:8901
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}

        - id: authentication-service
          uri: http://localhost:8787
          predicates:
              - Path=/authentication-service/**
          filters:
              - RewritePath=/authentication-service(?<segment>/?.*), $\{segment}
          
        - id: venue-service
          uri: http://localhost:8089
          predicates:
            - Path=/venue-service/**
          filters:
            - RewritePath=/venue-service(?<segment>/?.*), $\{segment}


        - id: recomendation-service
          uri: http://localhost:8081
          predicates:
            - Path=/recomendation-service/**
          filters:
            - RewritePath=/recomendation-service(?<segment>/?.*), $\{segment}

        - id: booking-service
          uri: http://localhost:8090
          predicates:
            - Path=/booking-service/**
          filters:
            - RewritePath=/booking-service(?<segment>/?.*), $\{segment}

        - id: payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/payment-service/**
          filters:
            - RewritePath=/payment-service(?<segment>/?.*), $\{segment}

        - id: email-service
          uri: http://localhost:8092
          predicates:
            - Path=/email-service/**
          filters:
            - RewritePath=/email-service(?<segment>/?.*), $\{segment}
